apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-env-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-env-app
  template:
    metadata:
      labels:
        app: docker-env-app
    spec:
      containers:
      - name: docker-env-container
        image: wasantalal/python-env-app
        imagePullPolicy: Always
        ports:
        - containerPort: 9000