apiVersion: v1
kind: Service
metadata:
  name: docker-env-service
spec:
  type: NodePort
  selector:
    app: docker-env-app
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30009